# Generated by Django 3.0.5 on 2023-07-27 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='clients',
            fields=[
                ('shop_id', models.IntegerField(primary_key=True, serialize=False)),
                ('shop_name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('phone_no', models.IntegerField()),
                ('email', models.EmailField(max_length=254, null=True)),
            ],
        ),
    ]
