# Generated by Django 3.0.5 on 2023-07-28 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clients',
            name='image',
            field=models.CharField(default='https://th.bing.com/th/id/OIP.kqT6XFsG2BTW22Y4st2-KAHaHa?pid=ImgDet&rs=1', max_length=1000),
        ),
    ]
