# Generated by Django 3.0.5 on 2023-08-03 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0002_clients_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='clients',
            name='balance',
            field=models.IntegerField(default=0),
        ),
    ]
