# Generated by Django 3.0.5 on 2023-08-03 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0003_clients_balance'),
    ]

    operations = [
        migrations.CreateModel(
            name='transaction',
            fields=[
                ('shop_id', models.IntegerField(primary_key=True, serialize=False)),
                ('transaction', models.CharField(max_length=10000)),
                ('amount', models.IntegerField(default=0)),
                ('balance', models.IntegerField(default=0)),
            ],
        ),
    ]
