# Generated by Django 3.0.5 on 2023-08-11 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0004_transaction'),
    ]

    operations = [
        migrations.DeleteModel(
            name='transaction',
        ),
        migrations.AddField(
            model_name='clients',
            name='amount',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='clients',
            name='transaction',
            field=models.CharField(default='null', max_length=10000),
        ),
    ]
